#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):
    minn, maxx = scores[0], scores[0]
    min_cnt, max_cnt = 0,0

    for score in scores:
        if score > maxx:
            maxx = score
            max_cnt += 1
        if score < minn:
            minn = score
            min_cnt += 1
     
    return [max_cnt, min_cnt]
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
