#!/bin/python3

import requests
from bs4 import BeautifulSoup
import pandas as pd


url = 'https://www.pro-football-reference.com'
year = 2021
maxp = 150

r = requests.get(url + '/years/' + str(year) + '/fantasy.htm')
soup = BeautifulSoup(r.content, 'html.parser')
parsed_table = soup.find_all('table')[0]

df = []
positions = ['RB', 'WR', 'QB']

for i, row in enumerate(parsed_table.find_all('tr')[2:]):
    if i % 10 == 0:
        print(i, end=' ')
    if i >= maxp:
        print('\nComplete.')
        break

    try:
        dat = row.find('td', attrs={'data-stat': 'player'})
        name = dat.a.get_text()
        print(name)
        stub = dat.a.get('href')
        stub = stub[:-4] + '/gamelog/2021/'
        pos = row.find('td', attrs={'data-stat': 'fantasy_pos'}).get_text()

        tdf = pd.read_html(url + stub)[0]
        tdf.columns = tdf.columns.get_level_values(-1)
        tdf.drop(tdf.tail(1).index, inplace=True)
        if pos == 'RB':
            tdf = tdf.iloc[:, [7, 10, 11, 13]]
            df.append(tdf)
        if pos == 'WR':
            tdf = tdf.iloc[:, [7, 10, 11, 12, 14]]
            df.append(tdf)
        if pos == 'QB':
            tdf = tdf.iloc[:, [7, 10, 11, 13, 14, 15]]
            df.append(tdf)
        tdf['Name'] = name
        tdf['Position'] = pos

    except AttributeError:
        pass

df = pd.concat(df)
print(df)

# noinspection PyTypeChecker
df.to_csv('/Users/arslanamir/PycharmProjects/nfl.csv', index=False)
